# Generated by Django 5.0.1 on 2024-03-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='status',
            field=models.CharField(choices=[('Disponivel', 'Disponivel'), ('Indisponivel', 'Indisponivel')], max_length=20),
        ),
    ]
